/**
 * App Redux Action Types
 */

/**
 * API interface Action
 */
export const UPDATE_METHOD = 'UPDATE_METHOD';
export const SET_URLADDRESS = 'SET_URLADDRESS';
export const SEND_REQUEST = 'SEND_REQUEST';
export const UPDATE_PARAMS = 'UPDATE_PARAMS';
export const SET_PARAMS_ROWS_SELECTED = 'SET_PARAMS_ROWS_SELECTED';
export const UPDATE_HEADERS = 'UPDATE_HEADERS';
export const SET_HEADERS_ROWS_SELECTED = 'SET_HEADERS_ROWS_SELECTED';
export const SET_BODY_TYPE = 'SET_BODY_TYPE';
export const UPDATE_FORMDATA = 'UPDATE_FORMDATA';
export const SET_FORMDATA_ROWS_SELECTED = 'SET_FORMDATA_ROWS_SELECTED';
export const UPDATE_URLENCODED = 'UPDATE_URLENCODED';
export const SET_URLENCODED_ROWS_SELECTED = 'SET_URLENCODED_ROWS_SELECTED';
export const API_RESPONSE_FAIL = 'API_RESPONSE_FAIL';
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const UPDATE_RAWBODY = 'UPDATE_RAWBODY';
export const CSV_RESPONSE_FAIL = 'CSV_RESPONSE_FAIL';
export const CSV_RESPONSE_SUCCESS = 'CSV_RESPONSE_SUCCESS';
export const SELECT_API = 'SELECT_API';
